<a href="https://colab.research.google.com/github/yazan-95/PythonUniversityUseOf/blob/main/NumpyRev2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# x = np.array([[1,2],[2,3]])
# print("Original array:")
# print(x)
# print("Sum of all elements:")
# print(np.sum(x))
# print("Sum of each column:")
# print(np.sum(x, axis=0))
# print("Sum of each row:")
# print(np.sum(x, axis=1))

Original array:
[[1 2]
 [2 3]]
Sum of all elements:
8
Sum of each column:
[3 5]
Sum of each row:
[3 5]


In [ ]:
FQ = np.arange(50)
arr4 = np.reshape(FQ,(5,10))
print("Original array :")
print(arr4)
print("-"*100)
print("Sum of all elements =",arr4.sum())
print("-"*100)
print("Sum of each row =",arr4.sum(axis=1))
print("-"*100)
print("Sum of each column =",arr4.sum(axis=0))


Original array :
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
----------------------------------------------------------------------------------------------------
Sum of all elements = 1225
----------------------------------------------------------------------------------------------------
Sum of each row = [ 45 145 245 345 445]
----------------------------------------------------------------------------------------------------
Sum of each column = [100 105 110 115 120 125 130 135 140 145]
