<a href="https://colab.research.google.com/github/yazan-95/PythonUniversityUseOf/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
####    Question 1    ####

import numpy as np


In [2]:

arr = np.arange(10,22)

arr.reshape((3,4))

####    Question 2    ####


arr2 = np.eye(3)

(arr2)

####    Question 3    ####

arr3 = np.ones(shape=(10,10))

for i in range(1,9):
    for k in range(1,9):
        arr3[k,i]=0
(arr3)

####    Question 4    ####

a = np.random.random((3,3,3))
print(a)

####    Question 5    ####


FQ = np.arange(50)
arr4 = np.reshape(FQ,(5,10))
print("Original array :")
print(arr4)
print("-"*100)
print("Sum of all elements =",arr4.sum())
print("-"*100)
print("Sum of each row =",arr4.sum(axis=1))
print("-"*100)
print("Sum of each column =",arr4.sum(axis=0))

[[[0.14545143 0.47393079 0.19909816]
  [0.60818274 0.57307268 0.05064434]
  [0.24244913 0.71586542 0.76151656]]

 [[0.38949126 0.81960509 0.15299764]
  [0.45424952 0.01843372 0.24474099]
  [0.88789602 0.23998109 0.87199594]]

 [[0.64711098 0.83482948 0.47663666]
  [0.74674879 0.12405673 0.03533309]
  [0.87228065 0.1654416  0.41016151]]]
Original array :
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
----------------------------------------------------------------------------------------------------
Sum of all elements = 1225
----------------------------------------------------------------------------------------------------
Sum of each row = [ 45 145 245 345 445]
----------------------------------------------------------------------------------------------------
Sum of each column = [100 105 110 115 120 125 130 135 140 145]




```
# This is formatted as code
```

# New Section

# New Section

# New Section